### ISSUE TITLE
Can you help me with your script to build PDFium?

### ISSUE THREAD

**Issue by mudlej** [benjinus/android-support-pdfium#11]
I created an app called MJ PDF Reader that uses [PdfiumAndroid](https://github.com/barteksc/PdfiumAndroid). I forked the project to update it [libs](https://gitlab.com/mudlej_android/mj_pdf_reader#forking-pdfiumandroid). However, I couldn't build Pdfium.

I found your project which has a script for that. After a simple change in the script from `ninja -C out pdfsdk` to `ninja -C out fpdfsdk`, everything works perfectly until the last step, it gives the following error:
```
ld.lld: error: unable to find library -latomic
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
I tried to do everything I could think of, but nothing worked. Do you know how to solve this issue?

**Comment by woheller69** [comment]
why did you change to fpdfsdk? Don't you want to build pdfsdk?
fpdfsdk seems to be a dependency if I get it right.

    shared_library("pdfsdk") {
      deps = [":pdfium"]
      ldflags = [ "-latomic" ]




deps = [
--
  | "constants",
  | "core/fpdfapi/page",
  | "core/fpdfapi/parser",
  | "core/fpdfdoc",
  | "core/fxcodec",
  | "core/fxcrt",
  | "core/fxge",
  | "**fpdfsdk**",
  | "fpdfsdk/formfiller",
  | "fxjs",
  | "third_party:pdfium_base",
  | "third_party:skia_shared",
  | ]

**Comment by mudlej** [comment]
First, thanks for replying, I was getting so frustrated with this problem.
Second, I changed it because it gave me the following error
```
ninja: warning: bad deps log signature or version; starting over
ninja: error: unknown target 'pdfsdk', did you mean 'fpdfsdk'?
```
 When I changed it, it went through with no problem, but it keeps failing at the last step because of the atomic lib.

And about what I want to do, just building the new version of PDFium with the same configuration [PdfiumAndroid](https://github.com/barteksc/PdfiumAndroid) used.

**Comment by mudlej** [comment]
I tried changing it back to pdfsdk in these places:
```
// at BUILD.gn
shared_library("pdfsdk") {    // <---- here
  deps = [":pdfium"]
  ldflags = [ "-latomic" ]
```
and here:
```
// at build.sh
ninja -C out pdfsdk     // <---- here
```
The same thing happend, did all the steps but at the end:
```
[73/73] SOLINK ./libpdfsdk.so
FAILED: libpdfsdk.so libpdfsdk.so.TOC lib.unstripped/libpdfsdk.so lib.unstripped/libpdfsdk.so.map.gz
python3 "../build/toolchain/gcc_solink_wrapper.py" --readelf="../third_party/llvm-build/Release+Asserts/bin/llvm-readelf" --nm="../third_party/llvm-build/Release+Asserts/bin/llvm-nm" --strip=../third_party/llvm-build/Release+Asserts/bin/llvm-strip  --sofile="./lib.unstripped/libpdfsdk.so" --tocfile="./libpdfsdk.so.TOC" --map-file "./lib.unstripped/libpdfsdk.so.map.gz" --output="./libpdfsdk.so" -- ../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-soname="libpdfsdk.so" -latomic -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=5 -march=armv5 -Wl,--no-rosegment -Wl,--no-call-graph-profile-sort -Wl,--exclude-libs=libvpx_assembly_arm.a --unwindlib=none --target=arm-linux-androideabi23 -no-canonical-prefixes -Wl,--warn-shared-textrel -Wl,-O2 -Wl,--gc-sections -Wl,-z,defs -Wl,--as-needed -nostdlib++ --sysroot=../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Wl,--warn-shared-textrel -Wl,--lto-O0 -o "./lib.unstripped/libpdfsdk.so" @"./libpdfsdk.so.rsp"
ld.lld: error: unable to find library -latomic
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by woheller69** [comment]
maybe libatomic or the corresponding developer library is not installed on your system?
Or not in the path where the linker is searching for it?

**Comment by mudlej** [comment]
I thought this is the problem.
I have these installed on my system
```
libatomic_ops 7.6.14-1
clang 14.0.6-2
lib32-clang 14.0.6-1
```
and 
```
libatomic1
```

I searched for it:
```
usr/lib/libatomic.so.1
usr/lib/libboost_atomic.so
usr/lib/libatomic_ops_gpl.so.1
usr/lib/libatomic.so
usr/lib/libboost_atomic.a
usr/lib/go/pkg/linux_amd64/sync/atomic.a
usr/lib/libatomic.so.1.2.0
usr/lib/go/test/atomicload.go
usr/lib/go/test/escape_runtime_atomic.go
usr/lib/go/test/intrinsic_atomic.go
...
```
And this is my path.
```
'/usr/lib:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-ndk:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
```

I tried Debian, Arch and Ubuntu. Same error.

**Comment by mudlej** [comment]
Is there a way to build it using gcc? I think it may work.

**Comment by woheller69** [comment]
Maybe yiou need to specify the path or export the library path?

**Comment by mudlej** [comment]
Is there any specific path I should export? I tried the ones I am aware of.

`'/usr/lib:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-ndk:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'`

**Comment by woheller69** [comment]
LD_LIBRARY_PATH should probably be exported and contain the path to the libs

**Comment by mudlej** [comment]
```
$ export LD_LIBRARY_PATH=/usr/lib64:/usr/lib32:/usr/local/lib:/usr/lib
$ sudo ldconfig
$ ./build.sh
```
Same error:
```
ld.lld: error: unable to find library -latomic
```

**Comment by woheller69** [comment]
what about the build script from here? https://gitlab.com/axet/android-pdfium
According to build.diff ldflags is empty
+shared_library("modpdfium") {
+  deps = [":pdfium"]
+  ldflags = []
+  configs -= [ "//build/config/android:hide_all_but_jni_onload" ]
+}

**Comment by mudlej** [comment]
That was a great idea, but unfortunately, it just gave me an error which means the same thing.
```
ld.lld: error: undefined symbol: __atomic_fetch_add_4
>>> referenced by shared_ptr.h:121 (../buildtools/third_party/libc++/trunk/include/__memory/shared_ptr.h:121)
>>>               thinlto-cache/llvmcache-676973F143D7C606978F87877D32977FF0E0D12C:(long std::Cr::__libcpp_atomic_refcount_decrement<long>(long&))
>>> referenced by shared_ptr.h:110 (../buildtools/third_party/libc++/trunk/include/__memory/shared_ptr.h:110)
>>>               thinlto-cache/llvmcache-676973F143D7C606978F87877D32977FF0E0D12C:(long std::Cr::__libcpp_atomic_refcount_increment<long>(long&))
>>> referenced by atomic_support.h:82 (../buildtools/third_party/libc++/trunk/src/include/atomic_support.h:82)
>>>               thinlto-cache/llvmcache-A99B99D44C88D24EE62A39064C48F011D7CC2BA9:(std::Cr::locale::id::__init())
>>> referenced 2 more times
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed. 
```

**Comment by mudlej** [comment]
Finally, I found another [script](https://github.com/bblanchon/pdfium-binaries) that with some tweaking I got it to build.

Unfortunately, for some reason the rendering has a lag right now when zooming the pdf in and out.

Thanks so much for your help, really appreciate your time.

**Comment by woheller69** [comment]
Great, hope to see MJPDF on F-Droid soon
