### ISSUE TITLE
Can you add the x86-64 bit .so files please?

### ISSUE THREAD

**Issue by faltiska** [benjinus/android-support-pdfium#5]
Or can you please document how you built the .so files?
I see you are using a different set of files than barteksc/PdfiumAndroid and I am not sure where / how to get the 64bit version.

Apparently google play requires 64bit libraries to publish apps...

Thank you!

**Comment by faltiska** [comment]
I would try and build pdfium myself but I don't know how.

I was thinking to get a newer version, in case they fixed some bugs and also to try and and the x86-64 libraries too.

Can you give me a few pointers to get me started, please ?

**Comment by jasolgar84** [comment]
Can you tell us how to build the .so files by our self? 

Thanks

**Comment by benjinus** [comment]
> Can you tell us how to build the .so files by our self?
> 
> Thanks

**Comment by jasolgar84** [comment]
I've compiled Pdfium with x86_64 architecture, but it doesn't work. I can compile the library using x86_64 binary file, but when I run the sample app, it crashes because of doesn't find **"libicuuc.cr.so"**

**Comment by benjinus** [comment]
@jasolgar84 check this link

[How to build PDFium library for Android](https://medium.com/@raju.kandasamy/how-to-build-pdfium-library-for-android-70e42ad31f6c)

**Comment by jasolgar84** [comment]
Hi, 

I followed that tutorial, but when I build the .so binary files and copy them into your project, I got the previous error mesage. In fact, the binary files its called "libpdfium.cr.so". 

Did you tried it to build following that tutorial?

**Comment by benjinus** [comment]
yes. i will update a how-to-build.md next week.

**Comment by jasolgar84** [comment]
Thank you

**Comment by benjinus** [comment]
I am working on it now, after i test it out, i will update the build guide file.

**Comment by benjinus** [comment]
@jasolgar84 @faltiska 
I have uploaded a BUILD.md file.

i am attaching the libs i just built, but i dont have enough time to test all libs.
[libpdfsdk.zip](https://github.com/benjinus/android-support-pdfium/files/5193742/libpdfsdk.zip)

**Comment by jasolgar84** [comment]
Thanks a lot. I will give you feedback when I can test it

**Comment by benjinus** [comment]
Closed as @jasolgar84's PR #6 has been merged.

**Comment by simonbellu** [comment]
@benjinus Hi, is the annotations api working with the latest .so files upgrade?
Thank you
